pipeline:
  agent:
    any: true
  stages:
    - stage: "Stage 1 -> Hello World"
      steps:
        - echo "stage 1 - hello world"
    - stage: "Stage2 -> test2"
      steps:
        - echo "stage 2 - test2"
